resolver: lts-19.6
packages:
- safe-coloured-text
- safe-coloured-text-gen
- safe-coloured-text-layout
- safe-coloured-text-layout-gen
- safe-coloured-text-terminfo

extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- github: NorfairKing/sydtest
  commit: 130de92053c1c3d60a8f45d509210415ffbea530
  subdirs:
  - sydtest
  - sydtest-discover

- github: NorfairKing/autodocodec
  commit: 479390d82e4fb2a404c497d6b9a9fec1505b1e5e
  subdirs:
  - autodocodec
  - autodocodec-schema
  - autodocodec-yaml

- github: NorfairKing/validity
  commit: d88be911a7e2a84f6c089e9269aaed8d10a74acd
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-criterion
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-hspec-persistent
  - genvalidity-path
  - genvalidity-persistent
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-hashable
  - genvalidity-sydtest-lens
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-persistent
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack
