name: safe-coloured-text-terminfo
version: 0.2.0.0
github: "NorfairKing/safe-coloured-text"
license: MIT
category: User Interfaces
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020 Tom Sydney Kerckhove"
synopsis: Safely output coloured text

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - safe-coloured-text
  - terminfo
