name: safe-coloured-text-layout
version: 0.2.0.1
github: "NorfairKing/safe-coloured-text"
license: MIT
category: User Interfaces
author: "Tom Sydney Kerckhove"
maintainer: "syd@cs-syd.eu"
copyright: "Copyright (c) 2020 Tom Sydney Kerckhove"
synopsis: Safely layout output coloured text

extra-source-files:
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - safe-coloured-text
  - text
  - validity
