name: "Stack Build"
on:
  pull_request:
  push:
    branches: 
      - development
      - master

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stack: ["2.3.1"]
        ghc: ["8.8.3"]

    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: actions/setup-haskell@v1.1.3
      name: Setup Haskell Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build dependencies
      run: |
        stack build --system-ghc --only-dependencies

    - name: Build autoexporter
      run: |
        stack install --system-ghc autoexporter

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    - name: Test
      run: |
        stack test --system-ghc
